spring:
  application:
    name: SimpleWeibo-backend

  profiles:
    active: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

jwt:
  secret: SimpleWeibo2026JwtSecretKeyForHmacSha256AlgorithmMin32Bytes
  expiration: 604800000  # 7天（毫秒）
